import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className="bg-slate-900 py-10 mb-10">
          <h1 className="text-6xl text-center text-amber-400">
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </header>

        <h2 className="text-4xl font-bold">
          This is a boilerplate by{" "}
          <a
            href="https://domthedev.com"
            target={"_blank"}
            rel="noopener noreferrer"
          >
            Dom the Dev
          </a>
        </h2>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
